[toolchain]
channel = "nightly-2023-04-02"
components = [ "rust-src", "rustfmt", "llvm-tools-preview" ]
targets = [
    "thumbv7em-none-eabi",
    # "thumbv7m-none-eabi",
    # "thumbv6m-none-eabi",
    # "thumbv7em-none-eabihf",
    # "thumbv8m.main-none-eabihf",
    # "wasm32-unknown-unknown",
]